name: Harriet — Fraue bei DiB
description: "Frauen(themen) bei DEMOKRATIE IN BEWEGUNG in Deiner Inbox!"
link: https://harriet.bewegung.jetzt/
source: "."
dest: "build"
rss: "rss.xml"
# post_path: ""

ignore:
  - .git/*
  - build/*
  - .deploy/*
  - generate.py
  - pip-selfcheck.json
  - bin
  - lib
  - include
  - requirements.txt
  - README.md
  - LICENSE
  - examples